server:
  port: 8088
spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  application:
    name: shopoo-spring-authorization-server-start
  cloud:
    nacos:
      username: ${NACOS_USERNAME}
      password: ${NACOS_PASSWORD}
      discovery:
        namespace: shopoo-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
      config:
        namespace: szmengran-${spring.profiles.active}
        server-addr: ${NACOS_SERVER_ADDRESS}
  config:
    import:
      - nacos:knife4j.yaml
      - nacos:wechat.yaml
      - nacos:shopoo-spring-authorization-server-start.yaml
